### ISSUE TITLE
Improve number display

### ISSUE THREAD

**Issue by halivert** [halivert/calculator-app#3]
**Description**

We need to improve the display of numbers so user can easily view the difference between the tens, hundreds, thousands and so on

**Acceptance criteria**

The display must have a comma when a group of three numbers (before decimal point) is displayed

**Examples**

<img width="541" alt="Screen Shot 2022-10-25 at 9 25 03" src="https://user-images.githubusercontent.com/16197249/197800405-3a6369b4-bab3-453b-b0bb-058d6ab94139.png">

<img width="519" alt="Screen Shot 2022-10-25 at 9 25 42" src="https://user-images.githubusercontent.com/16197249/197800591-2af759c6-c649-45b9-879e-14322bade92f.png">

**Comment by YashJain2409** [comment]
Can i work on this?

**Comment by halivert** [comment]
Sure @YashJain2409 👍🏽

**Comment by YashJain2409** [comment]
Hey @halivert , i have created pr ,you can review it.

**Comment by dpuentel** [comment]
This doesn't work as expected.

- Input "9999" the app show "9999" when it should be "9.999".
- Input "99999" the app show "99.999" when ir should be "99,999".

The dot, only there be to decimals otherwise the result will be unexpected

**Comment by halivert** [comment]
Hey @dpuentel, maybe the locale of your browser is different because this is implemented with [`toLocaleString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) so the PR solution is better than the described one, thank you anyway

**Comment by dpuentel** [comment]
> Hey @dpuentel, maybe the locale of your browser is different because this is implemented with [`toLocaleString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) so the PR solution is better than the described one, thank you anyway

My browser locale is 'es-ES'.

However, the locale should not influence the result of the operations, and with locale 'es-ES' it is not working correctly.

The locale 'es-ES' uses '.' to separate thousands. This causes an error interpreting it as decimals.

Check 2ad305814dbe7cb677b0e04bf5af568868e17302, which doesn't affect the values for the calculation, only the display, and also forces the locale to 'en'

**Comment by halivert** [comment]
Yes @dpuentel you're right, what do you think of change the decimal point in the keyboard instead?

**Comment by YashJain2409** [comment]
@halivert Can you explain issue you are getting ?

**Comment by halivert** [comment]
Yes @YashJain2409, when you try to use the locale string with locales that use decimal coma, instead decimal point, some issues arise because the point in the calculator keyboard doesn't change. 

I hope @dpuentel can upload a gif or screenshot showing us the actual issue.

**Comment by dpuentel** [comment]
> Yes @YashJain2409, when you try to use the locale string with locales that use decimal coma, instead decimal point, some issues arise because the point in the calculator keyboard doesn't change.
> 
> I hope @dpuentel can upload a gif or screenshot showing us the actual issue.

Of course. Here are some examples:
![low-chrome-capture-2022-9-26 (1)](https://user-images.githubusercontent.com/1440142/198040925-4096d122-c49b-4225-9393-2c027c132029.gif)
![low-chrome-capture-2022-9-26 (2)](https://user-images.githubusercontent.com/1440142/198040956-a08ad973-95c8-40c3-82a7-88a22acd1d24.gif)
![low-chrome-capture-2022-9-26](https://user-images.githubusercontent.com/1440142/198040982-aa4227ad-38c3-4417-918c-8489bc7db585.gif)

**Comment by YashJain2409** [comment]
ok got it thanks for explaining
